config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "homes#top"
  get 'home/about'=>'homes#about'

 resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
   resources :book_comments, only: [:create, :destroy]
   resource :favorites, only: [:create, :destroy]
 end

 resources :users, only: [:create, :index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
 end
 get "search" => "searches#search_result"
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user  #Comment.userでコメントの所有者を取得
  belongs_to :book  #Comment.postでそのコメントがされた投稿を取得

  validates :comment_content, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  # before_action :authenticate_user!, only: [:create]
   def create
    # @book = current_user.books.new(book_params)
    #   if @book.save
    #     redirect_back(fallback_location: root_path)
    #     redirect_back(fallback_location: root_path)
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to request.referer
   end

   def destroy
     BookComment.find(params[:id])
     redirect_to request.referer
   end

   private
     def book_comment_params
       params.require(:book_comment).permit(:comment_content)
      # params.require(:book).permit(:book_content)
     end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_form.html.erb
<%= form_with(model:[book, book_comment], local: true) do |f| %>
  <%= f.text_area :comment_content, rows:'5',placeholder: "コメントをここに", class: "w-100" %>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/book_comments/_index.html.erb
<table>
  <tbody>
      <% book.book_comments.each do |book_comment| %>
      <tr>

        <td>
          <%= link_to user_path(book_comment.user) do %>
            <%= image_tag book_comment.user.get_profile_image, size: "100x100" %><br>
            <%= book_comment.user.name %>
          <% end %>
        </td>
        <td><%= render "favorites/btn", book: @book %></td>
        <td><%= book_comment.comment_content %></td>
        <td>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
          <% end %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>